language: clojure
lein: lein2
sudo: false
install:
    - bash ./ext/travisci/install.sh ~/.lein/profiles.clj
jdk:
    - oraclejdk8
notifications:
    email: false
script:
    - bash ./ext/travisci/test.sh lein2
addons:
  postgresql: "9.4"
services: postgresql
sudo: false
